org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US -Dnet.minecraftforge.gradle.check.certs=false -Dhttps.protocols=TLSv1.2,TLSv1.3
org.gradle.daemon=true
org.gradle.parallel=false

minecraft_version=1.20.1

#fabric
fabric_loader_version=0.19.3
fabric_api_version=0.92.9+1.20.1

#forge
forge_version=47.4.10
mapping_channel=official
mapping_version=1.20.1

#neoforge
neo_version=20.6.125

mod_id=cursorcenteredfix
mod_name=CursorCentered Fix
mod_version=1.4.0
mod_logo=cursorcenteredfix.png
description=Fix the cursor centering issue that occasionally happens when opening a GUI.
sources_url=https://github.com/LitnhJacuzzi/CursorCentered-Fix
issues_url=https://github.com/LitnhJacuzzi/CursorCentered-Fix/issues
license=GPL 3.0
author=LitnhJacuzzi
maven_group=org.litnhjacuzzi.cursorcenteredfix