org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US
org.gradle.daemon=true
org.gradle.parallel=true

minecraft_version=1.21.9

#fabric
fabric_loader_version=0.17.2
fabric_version=0.133.14+1.21.9
yarn_mappings=1.21.9+build.1
loom_version=1.11-SNAPSHOT

#neoforge
neo_version=21.9.6-beta

mod_id=cursorcenteredfix
mod_name=CursorCentered Fix
mod_version=1.2.1
mod_logo=cursorcenteredfix.png
description=Fix the cursor centering issue that occasionally happens when opening a GUI.
sources_url=https://github.com/LitnhJacuzzi/CursorCentered-Fix
issues_url=https://github.com/LitnhJacuzzi/CursorCentered-Fix/issues
license=GPL 3.0
author=LitnhJacuzzi
maven_group=org.litnhjacuzzi.cursorcenteredfix