plugins {
	id 'net.minecraftforge.gradle' version '[6.0,6.2)'
	id 'org.spongepowered.mixin' version '0.7+'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
	mappings channel: "official", version: "1.16.5"
	copyIdeResources = true
}

dependencies {
    minecraft "net.minecraftforge:forge:1.16.5-36.2.42"
    
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    
    implementation project(':common')
}

mixin {
	disableTargetValidator = true
	overwriteErrorLevel = 'warn'
	add sourceSets.main, 'cursorcenteredfix.mixins.refmap.json'
	config 'cursorcenteredfix.mixins.json'
}

java {
	withSourcesJar()
	
	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8
}

project.jar {
	archiveFileName = "${mod_id}-${mod_version}-forge+1.16.5.jar"
	from (project(":common").sourceSets.main.output) {
		exclude '**/mixin/*.class'
		exclude '**/cursorcenteredfix.mixins.json'
	}
	
	manifest {
		attributes([
			"MixinConfigs": "cursorcenteredfix.mixins.json",
			"Specification-Title"		: mod_id,
			"Specification-Vendor"		: author,
			"Specification-Version"		: "1",
			"Implementation-Title"		: rootProject.name,
			"Implementation-Version"	: mod_version,
			"Implementation-Vendor"		: author,
			"Implementation-Timestamp"	: new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
}